# Generated by Django 4.0.2 on 2022-02-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripton',
            new_name='description',
        ),
    ]
